services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # Mount the whole project directory for development
      - .:/app
      # Mount the docker socket to allow app to control docker
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LLM_API_BASE=http://ollama:11434/v1
      # Set PYTHONPATH to ensure imports work correctly from the project root
      - PYTHONPATH=/app/src
    depends_on:
      ollama:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ollama:11434"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "ollama", "ps"]
      interval: 10s
      timeout: 5s
      retries: 5

  blender_runner:
    build:
      context: .
      dockerfile: blender/Dockerfile
    volumes:
      # Mount the workspace to share scripts and outputs
      - ./workspace:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    # This service is for on-demand runs. This default command just prints the version.
    command: ["--version"]

volumes:
  ollama_data: